name: Build python-ldap 3.4.5 CPython 3.9 Windows x64

on:
  workflow_dispatch:

env:
  OPENSSL_VER: openssl-3.5.7
  OPENLDAP_VER: openldap-2.4.59

  # Keep exact parity with UAT/PROD
  PYTHONLDAP_VER: python-ldap-3.4.5

  # Build ONLY CPython 3.9 Windows AMD64
  CIBW_BUILD: "cp39-win_amd64"

  CIBW_TEST_COMMAND: python -c "import ldap; print(ldap.__version__)"

  MSBUILDTREATHIGHERTOOLSVERSIONASCURRENT: 1

jobs:
  build_amd64:
    name: Build CPython 3.9 AMD64 wheel
    runs-on: windows-latest

    env:
      VS_PLATFORM: x64
      VS_PLATFORM_TOOLSET: v145
      VC_VER: 18.0
      OPENSSL_CONFIG: VC-WIN64A-masm

    steps:
      - uses: actions/checkout@v7

      - uses: microsoft/setup-msbuild@v3
        with:
          msbuild-architecture: x64

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Build OpenSSL
        run: build_openssl.cmd
        shell: cmd

      - name: Build OpenLDAP
        run: build_openldap.cmd
        shell: cmd

      - name: Prepare python-ldap
        run: build_python-ldap.cmd
        shell: cmd

      - name: Build CPython 3.9 wheel
        uses: pypa/cibuildwheel@v4.2.0
        env:
          CIBW_ARCHS_WINDOWS: AMD64
          CIBW_BUILD: "cp39-win_amd64"

      - name: Upload wheel
        uses: actions/upload-artifact@v7
        with:
          path: ./wheelhouse/*.whl
          name: python-ldap-3.4.5-cp39-win-amd64
